<?php

/**
 * @file
 * Supports CKEDITOR integration for the paragraphs module.
 */

/**
 * Implements hook_help().
 */
function paragraphs_ckeditor_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
  }
}

function paragraphs_ckeditor_form_field_config_edit_form_alter(&$form, $form_state) {
  $field_definition = $form_state->getBuildInfo()['callback_object']->getEntity();
  if ($field_definition->getType() == 'entity_reference_revisions') {
    $target_type = $field_definition->getFieldStorageDefinition()->getSetting('target_type');
    if ($target_type == 'paragraph') {
      $form['third_party_settings']['paragraphs_ckeditor'] = array(
        '#type' => 'fieldset',
        '#title' => t('Paragraphs CKEditor'),
      );

      $options = \Drupal::service('paragraphs_ckeditor.markup.text_manager')->getTextBundles();
      if ($options) {
        $form['third_party_settings']['paragraphs_ckeditor'] += array(
          '#type' => 'fieldset',
          '#title' => t('Paragraphs CKEditor'),
          'enabled' => array(
            '#type' => 'checkbox',
            '#title' => t('CKEditor Enabled'),
            '#description' => 'Enables CKEditor integration for this field.',
            '#default_value' => $field_definition->getThirdPartySetting('paragraphs_ckeditor', 'enabled'),
          ),
          'text_bundle' => array(
            '#type' => 'select',
            '#title' => t('Text Bundle'),
            '#description' => t('The bundle to use as text (markup) input.'),
            '#options' => $options,
            '#default_value' => $field_definition->getThirdPartySetting('paragraphs_ckeditor', 'text_bundle'),
            '#element_validate' => array(
              'paragraphs_ckeditor_field_config_edit_form_validate',
            ),
            '#states' => array(
              'visible' => array(
              ':input[name="third_party_settings[paragraphs_ckeditor][enabled]"]' => array('checked' => TRUE),
              ),
            ),
          ),
        );
      }
      else {
        $form['third_party_settings']['paragraphs_ckeditor'] += array(
          'message' => array(
            '#markup' => '<p>' . t('You must create a paragraph type that includes a single field of type "Text (formatted, long)", and make it available to this field in order to use CKEditor integration with this field.') . '</p>' .
            '<p>' . t('This type will be used to save plaintext content entered in the wysiwyg.') . '</p>',
          ),
        );
      }

      $form['#entity_builders'][] = 'paragraphs_ckeditor_field_config_edit_form_builder';
    }
  }
}

function paragraphs_ckeditor_field_config_edit_form_validate(&$element, $form_state) {
  $text_bundle = $form_state->getValue($element['#parents']);
  $target_bundles = $form_state->getValue(['settings', 'handler_settings', 'target_bundles']);
  if (!$target_bundles || !empty($target_bundles[$text_bundle])) {
    $text_field = \Drupal::service('paragraphs_ckeditor.markup.text_manager')->getBundleTextField($text_bundle);
    if ($text_field) {
      $parents = array_slice($element['#parents'], 0, -1);
      $parents[] = 'text_field';
      $form_state->setValue($parents, $text_field->getName());
      return;
    }
  }

  $form_state->setError($element, t('Selected text bundle is not allowed.'));
}

function paragraphs_ckeditor_field_config_edit_form_builder($entity_type, $entity, &$form, $form_state) {
  $settings = $form_state->getValue(['third_party_settings', 'paragraphs_ckeditor']);
  if (empty($settings['enabled'])) {
    $entity->unsetThirdPartySetting('paragraphs_ckeditor', 'enabled');
    $entity->unsetThirdPartySetting('paragraphs_ckeditor', 'text_bundle');
    $entity->unsetThirdPartySetting('paragraphs_ckeditor', 'text_field');
  }
}
